### ISSUE TITLE
getAllGauges route fails sporadically

### ISSUE THREAD

**Issue by mariuspod** [curvefi/curve-api#280]
when requesting the API for all gauges I'm seeing some sporadic error responses with `success:false`
I'm running this on a timer every 10 minutes and 2/10 calls are failing:
```shell
curl -H 'Content-Type: application/json' 'https://api.curve.fi/api/getAllGauges?blockchainId=ethereum'
```
```json
{
  "success":false,
  "err":"Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced."
}
```

I've checked the status page for the `getAllGauges` route but it says it was up 100% in the last 24 hours :wink: 
https://statuspage.freshping.io/59335-CurveAPI/check/735107?timefilter=24

**Comment by philippe-git** [comment]
Apologies for the very late reply! The technical setup at the time had been overgrown by the API and led to all sorts of instability issues. Since then we've reworked the API entirely, and everything should now be stable. Closing this issue as a result, but let us know if you have any issues at all!
