### ISSUE TITLE
Deposit Zappers for Meta pools in API

### ISSUE THREAD

**Issue by pata-eth** [curvefi/curve-api#315]
As an aggregator, I'd like to be able to pull the deposit zapper address for meta pools. Currently, we consume this info from https://github.com/curvefi/curve-api/blob/main/constants/pools/pools.js but we'd ideally consume it from the api. For example:

/api/getPools/ethereum/main

```json
{
{...}
{
"id": "22",
"address": "0x8474DdbE98F5aA3179B3B3F5942D724aFcdec9f6",
"name": "Curve.fi MUSD/3Crv",
"lpTokenAddress": "0x1AEf73d49Dedc4b1778d0706583995958Dc862e6",
"depositZapper": "0x803A2B40c5a9BB2B86DD630B274Fa2A9202874C2", <=== New
...
}
{...}
}
```

**Comment by philippe-git** [comment]
Hi, thanks for bringing this up! It turns out that the `getPools/chain/registry` endpoints already had the `zapAddress` property for each pool that has a zap, but there was a typo that prevented it from matching some pools, and the latest zaps were not included yet.

This is now resolved: all pools with zaps now have this property, everything is up to date!

**Comment by pata-eth** [comment]
thank you @philippe-git!
